load_module modules/ngx_http_modsecurity_module.so;

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    # ── ModSecurity: Detection Only ───────────────────────────────────────────
    modsecurity on;
    modsecurity_rules_file /etc/modsecurity.d/modsecurity.conf;
    modsecurity_rules_file /etc/modsecurity.d/owasp-crs/crs-setup.conf;
    modsecurity_rules_file /etc/modsecurity.d/owasp-crs/rules/*.conf;
    modsecurity_rules_file /etc/modsecurity.d/override.conf;

    # ── Headers de proxy ──────────────────────────────────────────────────────
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # ── SQLi Labs ─────────────────────────────────────────────────────────────

    # App1 — ShopFlow (VULN-1 a 4)
    server {
        listen 8081;
        server_name _;
        location / {
            proxy_pass http://sqli_app1:8081;
        }
    }

    # App2 — LibroBase (VULN-5 a 8)
    server {
        listen 8082;
        server_name _;
        location / {
            proxy_pass http://sqli_app2:8082;
        }
    }

    # App3 — NewsHub (VULN-9 a 12)
    server {
        listen 8083;
        server_name _;
        location / {
            proxy_pass http://sqli_app3:8083;
        }
    }

    # App4 — StaffPortal (VULN-13 a 16)
    server {
        listen 8084;
        server_name _;
        location / {
            proxy_pass http://sqli_app4:8084;
        }
    }

    # App5 — StockTrack (VULN-17 a 18)
    server {
        listen 8085;
        server_name _;
        location / {
            proxy_pass http://sqli_app5:8085;
        }
    }

    # ── NoSQL Labs (portas remapeadas) ────────────────────────────────────────

    # App1 — CipherNote (VULN-A, B)  →  acesso via :9081
    server {
        listen 9081;
        server_name _;
        location / {
            proxy_pass http://nosql_app1:8081;
        }
    }

    # App2 — PeopleDir (VULN-C, D)  →  acesso via :9082
    server {
        listen 9082;
        server_name _;
        location / {
            proxy_pass http://nosql_app2:8082;
        }
    }
}
